//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "board_enum")]
pub enum BoardEnum {
    #[sea_orm(string_value = "STRAW")]
    Straw,
    #[sea_orm(string_value = "STICKS")]
    Sticks,
    #[sea_orm(string_value = "BRICKS")]
    Bricks,
}
